#!/bin/bash

# https://gitlab.com/gitaarik/battery-health-notifications

# It works on Pop OS 20.04 running GNOME 3.36.8: https://www.youtube.com/watch?v=kj7PusE9Hs4

export $(xargs -0 -a "/proc/$(pgrep gnome-session -n -U $UID)/environ")
# export $(xargs -0 -a "/proc/1000/environ")

BATTERY_PATH=$(upower -e | grep battery)
LINE_POWER_PATH=$(upower -e | grep line_power)
BATTERY_PERCENTAGE=$(upower -i $BATTERY_PATH | grep 'percentage:' | awk '{ print $2 }' | sed 's/%//')
CABLE_PLUGGED=$(upower -i $LINE_POWER_PATH | grep -A2 'line-power' | grep online | awk '{ print $2 }')

if [[ $CABLE_PLUGGED == 'yes' ]]; then

    if [[ $BATTERY_PERCENTAGE -gt 90 ]]; then
        DISPLAY=:0 notify-send --urgency=critical "Battery optimization" "Battery reached 90%, unplug the power cable to optimize battery life."
    fi

else

    if [[ $BATTERY_PERCENTAGE -lt 20 ]]; then
        DISPLAY=:0 notify-send --urgency=critical "Battery optimization" "Battery is below 20%, plug in the power cable to optimize battery life."
    fi
fi
